# Generated by Django 6.0 on 2025-12-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(choices=[('joins', 'Large-Table JOIN Performance'), ('aggregation', 'Complex Aggregations'), ('complex_types', 'Nested JSON/Arrays'), ('io', 'High I/O Read'), ('partitioning', 'Partition Pruning')], max_length=50)),
                ('description', models.TextField()),
                ('test_query', models.TextField(help_text='Hive SQL query to execute')),
                ('record_count', models.BigIntegerField(default=1000000, help_text='Simulated record count')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scenario_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HiveConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('setting_key', models.CharField(help_text='Hive configuration key', max_length=200)),
                ('setting_value', models.CharField(help_text='Configuration value', max_length=200)),
                ('category', models.CharField(choices=[('join', 'Join Optimization'), ('aggregation', 'Aggregation'), ('io', 'I/O Optimization'), ('partitioning', 'Partitioning'), ('execution', 'Execution Engine'), ('other', 'Other')], max_length=50)),
                ('impact_level', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], default='medium', max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('setting_key', 'setting_value')},
            },
        ),
        migrations.CreateModel(
            name='QueryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_executed', models.TextField()),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('rows_processed', models.BigIntegerField(blank=True, null=True)),
                ('rows_returned', models.IntegerField(blank=True, null=True)),
                ('data_read_mb', models.FloatField(blank=True, help_text='Data read in MB', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('configurations_used', models.ManyToManyField(blank=True, to='hive_assessment.hiveconfiguration')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='hive_assessment.assessmentscenario')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(blank=True, max_length=50)),
                ('target_value', models.FloatField(blank=True, help_text='Target/goal value', null=True)),
                ('status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='hive_assessment.querybenchmark')),
            ],
            options={
                'ordering': ['benchmark', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('reason', models.TextField(help_text='Why this optimization is recommended')),
                ('expected_improvement', models.CharField(blank=True, max_length=200)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive_assessment.hiveconfiguration')),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='hive_assessment.querybenchmark')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
