# Generated by Django 6.0 on 2025-12-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('full', 'Full Import'), ('incremental', 'Incremental'), ('manual', 'Manual')], max_length=50)),
                ('source', models.CharField(default='hive', max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='HiveQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('query_type', models.CharField(choices=[('select', 'SELECT'), ('insert', 'INSERT'), ('create', 'CREATE'), ('other', 'Other')], max_length=50)),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('rows_returned', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('station_name', models.CharField(max_length=200)),
                ('country', models.CharField(help_text='ISO 3166 country code', max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField(blank=True, help_text='Elevation in meters', null=True)),
                ('is_coastal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='hive_climate.region')),
            ],
            options={
                'ordering': ['country', 'station_name'],
            },
        ),
        migrations.CreateModel(
            name='ClimateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField()),
                ('temp_max', models.FloatField(blank=True, help_text='Maximum temperature (°C)', null=True)),
                ('temp_min', models.FloatField(blank=True, help_text='Minimum temperature (°C)', null=True)),
                ('temp_mean', models.FloatField(blank=True, help_text='Mean temperature (°C)', null=True)),
                ('precipitation', models.FloatField(blank=True, help_text='Precipitation (mm)', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity (%)', null=True)),
                ('sea_surface_temp', models.FloatField(blank=True, help_text='Sea surface temperature (°C)', null=True)),
                ('ocean_salinity', models.FloatField(blank=True, help_text='Ocean salinity (PSU)', null=True)),
                ('data_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='hive_climate.weatherstation')),
            ],
            options={
                'ordering': ['-observation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='weatherstation',
            index=models.Index(fields=['country', 'region'], name='hive_climat_country_dd10e6_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherstation',
            index=models.Index(fields=['is_active'], name='hive_climat_is_acti_3c048f_idx'),
        ),
        migrations.AddIndex(
            model_name='climateobservation',
            index=models.Index(fields=['year', 'month'], name='hive_climat_year_fb1e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='climateobservation',
            index=models.Index(fields=['observation_date', 'station'], name='hive_climat_observa_e4ac11_idx'),
        ),
        migrations.AddIndex(
            model_name='climateobservation',
            index=models.Index(fields=['station', 'year'], name='hive_climat_station_e3fad0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='climateobservation',
            unique_together={('station', 'observation_date')},
        ),
    ]
